"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-05-25

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('budget_party_total', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('passengers', sa.JSON(), nullable=False),
    sa.Column('structures', sa.JSON(), nullable=False),
    sa.Column('blackout_ranges', sa.JSON(), nullable=False),
    sa.Column('validation_tolerance_pct', sa.Integer(), nullable=False),
    sa.Column('validation_top_n', sa.Integer(), nullable=False),
    sa.Column('envelope_long_gap_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('origins', sa.JSON(), nullable=False),
    sa.Column('destinations', sa.JSON(), nullable=False),
    sa.Column('date_anchor', sa.String(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('sampling_strategy', sa.String(), nullable=False),
    sa.Column('return_date_anchor', sa.String(), nullable=True),
    sa.Column('return_window_days', sa.Integer(), nullable=True),
    sa.Column('return_sampling_strategy', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('scraper_calls', sa.Integer(), nullable=False),
    sa.Column('serpapi_calls', sa.Integer(), nullable=False),
    sa.Column('serpapi_quota_remaining', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('leg_ordinal', sa.Integer(), nullable=False),
    sa.Column('structure', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('return_date', sa.String(), nullable=True),
    sa.Column('carrier', sa.String(), nullable=False),
    sa.Column('price_per_pax', sa.Integer(), nullable=False),
    sa.Column('price_party', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('stops', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('passengers_queried', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fare', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fare_run_id'), ['run_id'], unique=False)

    op.create_table('itinerary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('structure', sa.String(), nullable=False),
    sa.Column('total_party_price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('fare_ids', sa.JSON(), nullable=False),
    sa.Column('gateway', sa.String(), nullable=True),
    sa.Column('train_to_venice', sa.JSON(), nullable=True),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itinerary_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itinerary_run_id'))

    op.drop_table('itinerary')
    with op.batch_alter_table('fare', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fare_run_id'))

    op.drop_table('fare')
    op.drop_table('run')
    op.drop_table('leg')
    op.drop_table('config')
    # ### end Alembic commands ###
